global:
  scrape_interval:     5s # How frequently to scrape targets by default.
  evaluation_interval: 60s # How frequently to evaluate rules by default.

scrape_configs:
  - job_name: 'world-service-process'
    static_configs:
      - targets: ['100.115.92.204:5260']
    metrics_path: '/grid/process'
  - job_name: 'world-service-layer-telemetry'
    static_configs:
      - targets: ['100.115.92.204:5260']
    metrics_path: '/grid/metrics}'
